// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCabff7D5k_tgEYrhX_MtKemv7BDFoabgs',
    appId: '1:195869521790:web:e1a40f03a79ae7c4eae52f',
    messagingSenderId: '195869521790',
    projectId: 'roomy-ai-23077',
    authDomain: 'roomy-ai-23077.firebaseapp.com',
    storageBucket: 'roomy-ai-23077.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxkRUMgD2abswoi53mo-eQ44kXphWmOKQ',
    appId: '1:195869521790:android:2ca4cbf38529906deae52f',
    messagingSenderId: '195869521790',
    projectId: 'roomy-ai-23077',
    storageBucket: 'roomy-ai-23077.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6hrSN9bpGOZdn_BRRbZtu8hdVOFXYOZw',
    appId: '1:195869521790:ios:9dbc24be2b254726eae52f',
    messagingSenderId: '195869521790',
    projectId: 'roomy-ai-23077',
    storageBucket: 'roomy-ai-23077.firebasestorage.app',
    iosBundleId: 'com.example.roomyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCabff7D5k_tgEYrhX_MtKemv7BDFoabgs',
    appId: '1:195869521790:web:19198b13972bafa1eae52f',
    messagingSenderId: '195869521790',
    projectId: 'roomy-ai-23077',
    authDomain: 'roomy-ai-23077.firebaseapp.com',
    storageBucket: 'roomy-ai-23077.firebasestorage.app',
  );
}
